language: python

services:
  - docker

before_install:
- docker-compose -f local.yml run app /bin/bash -c "cd /usr/src/app/ && ./entrypoint"

script:
- docker-compose -f local.yml run --rm app ./manage.py test --settings=config.settings.test "$@"