language: python

services:
  - docker

before_install:
- docker pull gcr.io/setlist-spy/setlistspy_api
- docker-compose run app /bin/sh -c "./entrypoint"
- docker-compose run --rm app ./manage.py test --settings=setlistspy.test_settings "$@"

script:
- docker-compose -f local.yml run --rm app ./manage.py test --settings=config.settings.test "$@"